import { Characteristic } from "../../../domain/entities/Characteristic";

export const characteristicsData: Characteristic[] = [
	{
		id: "strength",
		label: "strength",
		mod: [
			{ value: 3, mod: -3 },
			{ value: 4, mod: -2 },
			{ value: 5, mod: -2 },
			{ value: 6, mod: -1 },
			{ value: 7, mod: -1 },
			{ value: 8, mod: -1 },
			{ value: 9, mod: 0 },
			{ value: 10, mod: 0 },
			{ value: 11, mod: 0 },
			{ value: 12, mod: 0 },
			{ value: 13, mod: 1 },
			{ value: 14, mod: 1 },
			{ value: 15, mod: 1 },
			{ value: 16, mod: 2 },
			{ value: 17, mod: 2 },
			{ value: 18, mod: 3 },
			{ value: 19, mod: 3 },
		],
	},
	{
		id: "dexterity",
		label: "dexterity",
		mod: [
			{ value: 3, modArmor: 3, mod: -3, init: -2 },
			{ value: 4, modArmor: 2, mod: -2, init: -1 },
			{ value: 5, modArmor: 2, mod: -2, init: -1 },
			{ value: 6, modArmor: 1, mod: -1, init: -1 },
			{ value: 7, modArmor: 1, mod: -1, init: -1 },
			{ value: 8, modArmor: 1, mod: -1, init: -1 },
			{ value: 9, modArmor: 0, mod: 0, init: 0 },
			{ value: 10, modArmor: 0, mod: 0, init: 0 },
			{ value: 11, modArmor: 0, mod: 0, init: 0 },
			{ value: 12, modArmor: 0, mod: 0, init: 0 },
			{ value: 13, modArmor: -1, mod: 1, init: 1 },
			{ value: 14, modArmor: -1, mod: 1, init: 1 },
			{ value: 15, modArmor: -1, mod: 1, init: 1 },
			{ value: 16, modArmor: -2, mod: 2, init: 1 },
			{ value: 17, modArmor: -2, mod: 2, init: 1 },
			{ value: 18, modArmor: -3, mod: 3, init: 2 },
			{ value: 19, modArmor: -3, mod: 3, init: 2 },
		],
	},
	{
		id: "constitution",
		label: "constitution",
		mod: [
			{ value: 3, mod: -3 },
			{ value: 4, mod: -2 },
			{ value: 5, mod: -2 },
			{ value: 6, mod: -1 },
			{ value: 7, mod: -1 },
			{ value: 8, mod: -1 },
			{ value: 9, mod: 0 },
			{ value: 10, mod: 0 },
			{ value: 11, mod: 0 },
			{ value: 12, mod: 0 },
			{ value: 13, mod: 1 },
			{ value: 14, mod: 1 },
			{ value: 15, mod: 1 },
			{ value: 16, mod: 2 },
			{ value: 17, mod: 2 },
			{ value: 18, mod: 3 },
			{ value: 19, mod: 3 },
		],
	},
	{
		id: "intelligence",
		label: "intelligence",
		mod: [
			{ value: 3, mod: -3 },
			{ value: 4, mod: -2 },
			{ value: 5, mod: -2 },
			{ value: 6, mod: -1 },
			{ value: 7, mod: -1 },
			{ value: 8, mod: -1 },
			{ value: 9, mod: 0 },
			{ value: 10, mod: 0 },
			{ value: 11, mod: 0 },
			{ value: 12, mod: 0 },
			{ value: 13, mod: 1 },
			{ value: 14, mod: 1 },
			{ value: 15, mod: 1 },
			{ value: 16, mod: 2 },
			{ value: 17, mod: 2 },
			{ value: 18, mod: 3 },
			{ value: 19, mod: 3 },
		],
	},
	{
		id: "wisdom",
		label: "wisdom",
		mod: [
			{ value: 3, mod: -3 },
			{ value: 4, mod: -2 },
			{ value: 5, mod: -2 },
			{ value: 6, mod: -1 },
			{ value: 7, mod: -1 },
			{ value: 8, mod: -1 },
			{ value: 9, mod: 0 },
			{ value: 10, mod: 0 },
			{ value: 11, mod: 0 },
			{ value: 12, mod: 0 },
			{ value: 13, mod: 1 },
			{ value: 14, mod: 1 },
			{ value: 15, mod: 1 },
			{ value: 16, mod: 2 },
			{ value: 17, mod: 2 },
			{ value: 18, mod: 3 },
			{ value: 19, mod: 3 },
		],
	},
	{
		id: "charisma",
		label: "charisma",
		mod: [
			{ value: 3, mod: -3, assistant: 1, moral: 4 },
			{ value: 4, mod: -2, assistant: 2, moral: 5 },
			{ value: 5, mod: -2, assistant: 2, moral: 5 },
			{ value: 6, mod: -1, assistant: 3, moral: 6 },
			{ value: 7, mod: -1, assistant: 3, moral: 6 },
			{ value: 8, mod: -1, assistant: 3, moral: 6 },
			{ value: 9, mod: 0, assistant: 4, moral: 7 },
			{ value: 10, mod: 0, assistant: 4, moral: 7 },
			{ value: 11, mod: 0, assistant: 4, moral: 7 },
			{ value: 12, mod: 0, assistant: 4, moral: 7 },
			{ value: 13, mod: 1, assistant: 5, moral: 8 },
			{ value: 14, mod: 1, assistant: 5, moral: 8 },
			{ value: 15, mod: 1, assistant: 5, moral: 8 },
			{ value: 16, mod: 2, assistant: 6, moral: 9 },
			{ value: 17, mod: 2, assistant: 6, moral: 9 },
			{ value: 18, mod: 3, assistant: 7, moral: 10 },
			{ value: 19, mod: 3, assistant: 7, moral: 10 },
		],
	},
];
